[package]
name = "lab1-vectorization"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
ndarray = { workspace = true }
ndarray-rand = "*"
rand = "*"