[package]
name = "lab1-cfrs"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
ndarray = { workspace = true }
csv = "1.3.1"
ndarray-csv = "0.5.1"