[workspace]
members = [
    "supervised-learning/module1/l1-intro",
    "supervised-learning/module1/lab2-model-representation",
]
resolver = "3"

[workspace.package]
edition = "2024"
authors = ["Gaurav Kumar <gauravsingh12341@gmail.com>"]
description = "Rust implementations of all labs for Andrew Ng's Coursera Machine Learning course."
