[package]
name = "lab2-tree-ensemble"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
csv = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
smartcore = "0.4.2"
