[package]
name = "lab6-gradient-descent"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
ndarray = { workspace = true }
lab2-sigmoid = { path = "../lab2-sigmoid" }