[package]
name = "lab2-sigmoid"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
lab4-fe-and-pr = { path = "../../module2/lab4-fe-and-pr" }
ndarray = { workspace = true }
plotters = "*"
