[package]
name = "lab2-anomaly-detection"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
ndarray = { workspace = true }
ndarray-npy = "0.8"
