[package]
name = "lab3-decision-boundary"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
ndarray = { workspace = true }
plotters = "*"
