[package]
name = "lab3-fs-and-lr"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
ndarray = { workspace = true }
csv = "*"
lab2-mvlr = { path = "../lab2-mvlr" }