[package]
name = "lab3-coffe-roasting-simple"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
lab2-coffe-roasting = { path = "../lab2-coffe-roasting" }
lab2-sigmoid = { path = "../../../supervised-learning/module3/lab2-sigmoid" }
