[package]
name = "practice-w4-decision-tree"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
lab1-decision-tree = { path = "../lab1-decision-tree" }
