[package]
name = "lab7-linfa-logistic-regression"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
linfa = "0.7.0"
linfa-logistic = "0.7.0"
ndarray = { workspace = true }