[package]
name = "lab4-gradient-descent"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
ndarray = "*"
plotters = "*"
lab3-cost-function = { path = "../lab3-cost-function" }