[package]
name = "lab1-k-means"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
image = "0.25.8"
ndarray = { workspace = true }
ndarray-npy = "0.8"
rand = "0.8"
