[package]
name = "lab1-k-means"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
ndarray-npy = "0.8"
ndarray = { workspace = true }
rand = "0.8"