[package]
name = "lab9-regularization"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
ndarray = { workspace = true }
lab2-sigmoid = { path = "../lab2-sigmoid" }
lab2-mvlr = { path = "../../module2/lab2-mvlr" }