[package]
name = "lab4-fe-and-pr"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
ndarray = { workspace = true }
plotters = "*"
lab2-mvlr = { path = "../lab2-mvlr" }
lab3-fs-and-lr = { path = "../lab3-fs-and-lr" }