[package]
name = "practice-w2-linear-regression"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
lab2-mvlr = { path = "../lab2-mvlr" }
lab3-fs-and-lr = { path = "../lab3-fs-and-lr" }
ndarray = { workspace = true }
