name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev curl

      - name: Install chrome
        run: curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /tmp/chrome.deb && sudo apt install -y /tmp/chrome.deb

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Lint with clippy
        run: cargo clippy --workspace -- -D warnings

      - name: Build all crates
        run: cargo build --workspace --verbose --release

      - name: Run all labs
        run: |
          for crate in $(cargo metadata --no-deps --format-version 1 | jq -r '.packages[].name'); do
            echo "Running $crate..."
            cargo run -p "$crate" --release
          done

      - name: Run all tests
        run: cargo test --workspace --verbose --release