[package]
name = "lab1-classification"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
lab4-fe-and-pr = { path = "../../module2/lab4-fe-and-pr" }
linfa = "0.7.0"
linfa-linear = "0.7.0"
ndarray = { workspace = true }
